#!/bin/sh

# Please use DMD 2.077.1 or below when building the documentation.
#
# DMD 2.078.0 and up causes lots of duplicated symbols in the documentation.
# (See: https://github.com/rejectedsoftware/ddox/issues/208 )
#
# DMD 2.086.0 and up cause errors when building the docs because
# gen-package-version and Scriptlike need updated.

# Need taggedalgebraic
rm -rf ta
git clone https://github.com/s-ludwig/taggedalgebraic.git ta
rdmd --build-only -c -Isource -Ita/source -Dddocs_tmp -X -Xfdocs/docs.json -version=MySQLDocs --force source/mysql/package.d
rm -rf docs_tmp ta
rm source/mysql/package.o

dub --version
if ! dub run gen-package-version -- mysql --ddoc=ddoc --src=source; then
  echo "Failed to build gen-package-version"
  exit 1
fi
rm source/mysql/packageVersion.d

echo Building ddox...
cd ./ddox
if ! dub build; then
   echo "Failed to build ddox"
   exit 1
fi
cd ..
echo Done building ddox...

echo ddox filter...
./ddox/ddox -- filter docs/docs.json --min-protection Public
echo ddox generate-html...
./ddox/ddox -- generate-html docs/docs.json docs/public --navigation-type=ModuleTree --override-macros=ddoc/macros.ddoc --override-macros=ddoc/packageVersion.ddoc
